### ISSUE TITLE
desktop-idle with npm on windows

### ISSUE THREAD

**Issue by aannleax** [bithavoc/node-desktop-idle#1]
When trying to install desktop-idle on Windows with npm I get the following error:

Unsupported platform for desktop-idle@1.0.0: wanted {"os":"windows,linux,darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})

**Comment by bithavoc** [comment]
@aannleax what windows version are you trying to use? there's a few issues with windows, it's not passing CI for the architecture error you're seeing. additionally, the windows version is not reporting the idle with the same unit as linux and osx (milliseconds vs seconds).

If you give me until end of the day I can fix these.

**Comment by aannleax** [comment]
"what windows version are you trying to use"

**Comment by bithavoc** [comment]
@aannleax can you pay attention to the results here? https://github.com/bithavoc/node-desktop-idle/pull/2

**Comment by bithavoc** [comment]
@aannleax I just published `v1.1.0` with windows support.

Please re-open if you find the issue again. Also, can you check the behavior in Windows? I haven't had the chance.

**Comment by aannleax** [comment]
Seems like everything works now, thanks for the quick help.
