### ISSUE TITLE
Maximum number of clients reached

### ISSUE THREAD

**Issue by lucas91andrade** [bithavoc/node-desktop-idle#3]
Hello bithavoc, thanks for the nice pkg, was exactly what I was looking for.
But trying to run this on linux for some days now:

```
var desktopIdle = require('desktop-idle')
setInterval(function() {
  console.log(desktopIdle.getIdleTime())
}, 1000)
```

Keeps (after some seconds, failing into this):

```
┏ Electron -------------------

  1
  
┗ ----------------------------

┏ Electron -------------------

  Maximum number of clients reached

┗ ----------------------------
....
```

Keeps repeating "1", fills ram and crash PC... HAVOC ! ! heh.
Tried running it from node and from window, same behavior.

Any help much appreciated, thank you!

**Comment by bithavoc** [comment]
I may have a Memory leak in the number of X clients to I'm creating for the Linux path. Test suite needs to be imported for this.

**Comment by bithavoc** [comment]
@lucas91andrade please give `desktop-idle@1.1.1` a try, it includes the fix for the memory leak.
