### ISSUE TITLE
Add info about rebuild to README

### ISSUE THREAD

**Issue by kopylash** [bithavoc/node-desktop-idle#6]
Hello!

Can you please add the info that in some cases one need to rebuild the native module for electron to match the node version provided with electron?

```
node-gyp rebuild --target=1.7.10 --arch=x64 --dist-url=https://atom.io/download/atom-shell
```

Also referencing [this doc](https://github.com/electron/electron/blob/f403950503eb82bcfa230b13a909572beff75fc0/docs/tutorial/using-native-node-modules.md) will be helpful.

**Comment by bithavoc** [comment]
Hi, I haven't added those instructions since it's kinda different for each electron starter kit. Some strategies include two package.json files, etc
