### ISSUE TITLE
Support for arm architectures

### ISSUE THREAD

**Issue by ghisvail** [bithavoc/node-desktop-idle#8]
Are there any specific reasons as to why only x86 architectures are listed as supported?

Would it be possible to add support for arm-based architectures in the future?

Cheers,
Ghis

**Comment by bithavoc** [comment]
@ghisvail I can remove the restriction but I haven't really tried in ARM.

Would you like me to do that?

**Comment by bithavoc** [comment]
I don't think so @ghisvail 

I just published `desktop-idle@.1.1.2`, it's the first version without CPU restriction in package.json.

Would you be so kind to let me know if it works in ARM?

**Comment by bithavoc** [comment]
closing due inactivity.
