### ISSUE TITLE
Fail including this module in electron

### ISSUE THREAD

**Issue by mbuchner** [bithavoc/node-desktop-idle#9]
Hi - I tried using your lib in an electron build / angular application but I fail ...

    "electron": "^3.0.2",
    "electron-builder": "^20.28.4",
    "electron-reload": "^1.2.5",

following error pops up:
![image](https://user-images.githubusercontent.com/2117017/46424585-d414db00-c739-11e8-8640-1a04be542551.png)

Electron: (process.versions)
 { http_parser: '2.8.0',
  node: '10.2.0',
  v8: '6.6.346.32',
  uv: '1.20.3',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.1.0h',
  electron: '3.0.2',
  chrome: '66.0.3359.181' }

c:\_Entwicklung\Mattermost\matter-mon>node -v
v10.11.0

c:\_Entwicklung\Mattermost\matter-mon>npm -v
6.4.1

I already rebuild it with node 10 "npm i desktop-idle" but always get this error ...

**Comment by bithavoc** [comment]
Hi, I'm sorry this happened to you. I haven't tried in Electron 3, you may not this this module in Electron 3 since there is a new API to calculate the idle time. check it out https://electronjs.org/docs/api/power-monitor

Feel free to re-open if you still want to use it.

**Comment by mistersdevelopment** [comment]
Hi, I'm actually having the same issue.

I'm using Node 8.7.0 with Electron 1.8.1. Sadly I can't upgrade to Electron 3 due to other dependencies.

![windowsdesktopidleerrorelectron](https://user-images.githubusercontent.com/33233485/48145893-782dfc80-e279-11e8-8617-09817b4a2949.png)

Thanks!

**Comment by bithavoc** [comment]
@mistersdevelopment can you show me the stack trace in the console output?

**Comment by mistersdevelopment** [comment]
Running electron-rebuild has fixed the issue for me.
https://electronjs.org/docs/tutorial/using-native-node-modules#installing-modules-and-rebuilding-for-electron
```
# On Windows if you have trouble, try:
.\node_modules\.bin\electron-rebuild.cmd
```

**Comment by bithavoc** [comment]
Rebuilding is necessary so this mom module is compiled against electron’s Node runtime.
